# available directory themes:
# spearmint, peppermint, hemingway, brookmint
theme = 'spearmint'

[general]
title = "i18n.site.title"
logo = ""
iconLogo = "tabler:coffee"

[general.seo]
name = "i18n.site.seoName"
description = "i18n.site.seoDescription"
url = "https://nuxtstarters.com"

[directoryData.source]
name = "json"    # default, mock, sheets, json
links = "normal"

[directoryData.tagPages]
title = "i18n.directory.tagPagesTitle"

[directoryData.search]
placeholder = "i18n.common.searchPlaceholder"

[[directoryData.tags]]
key = "breathing"
name = "Breathing"
color = "blue"
emoji = "üëÉ"
description = "Breathing techniques are a popular feature in MeaMart."

[[directoryData.tags]]
key = "sleep"
name = "Sleep"
color = "green"
emoji = "üí§"
description = "Some apps include music that slowly goes away to help you sleep better and rest."

[[directoryData.tags]]
key = "meditation"
name = "Meditation"
color = "purple"
emoji = "üßò‚Äç‚ôÇÔ∏è"
description = "A meditation for your life. It's a great way to relax and clear your mind. It's also a great way to improve your sleep."

[[directoryData.tags]]
key = "yoga"
name = "Yoga"
color = "purple"
emoji = "üßò‚Äç‚ôÇÔ∏è"
description = "A yoga for your life."

[[directoryData.tags]]
key = "timer"
name = "Timer"
color = "green"
emoji = "‚è∞"
description = "Timers can be used to track how much you meditate."

[header.banner]
show = true
text = "i18n.header.bannerText"
link = "https://x.com/intent/follow?screen_name=mark_bruderer"
brandText = "i18n.header.bannerBrandText"

[header.navbar]
colorModeSelector = true

[[header.navbar.links]]
name = "i18n.nav.blog"
href = "/blog"

[[header.navbar.links]]
name = "i18n.nav.analytics"
href = "https://us.posthog.com/shared/vHlGCcSqPjGH4r_QijaXSETtmN9J-g"
target = "_blank"

[header.actionButton]
text = "i18n.header.actionButtonText"
href = "https://tally.so"

[footer]
description = "i18n.footer.description"

[footer.socials.x]
link = "https://x.com/mark_bruderer"

[footer.socials.youtube]
link = "https://www.youtube.com/@mark_hacks"
