[layout]
sidebar = false
emoji = false

[listings]
pageHeader = 'none' # none, title

[directoryUI.search]
placeholder = "i18n.common.searchPlaceholder"
showCount = true
icon = "tabler:bow"

[directoryUI.search.tags]
display = "show-all" # options: none,select,show-all
intersection = true

[directoryUI.grid]
list = false
type = "rectangle-card-grid" # options: icon-list, small-card-grid, rectangle-card-grid

[directoryUI.grid.emptyState]
text = "i18n.directory.emptyStateText"
type = "button"          # options: button, simple, link
icon = "tabler:exclamation-mark"

[directoryUI.grid.card]
image = true

[directoryUI.grid.submit]
show = true
first = false
title = "i18n.directory.submitTitle"
description = "i18n.directory.submitDescription"
hideable = true

[directoryUI.featured]
showOnAllPages = true
showOnSide = true
icon = "tabler:star"
labelForCard = "i18n.directory.featuredLabel"

[ui.icons]
dark = "tabler:moon"
light = "tabler:sun"
youtube = "tabler:brand-youtube"
x = "tabler:brand-twitter"
instagram = "tabler:brand-instagram"
facebook = "tabler:brand-facebook"
github = "tabler:brand-github"